### PR TITLE
Remove notes issue 71

### LINKED ISSUE #71: Remove notes section from charts.

### PR DESCRIPTION
**Pull request by macfarlandian**
@annaswigart @salspaugh no more notes in question cards or charts

- because nobody uses them
- editing logic remains in the controllers for now
- closes #71

### CODE REVIEW

**Comment by salspaugh** [comment]
When I went from your other branch for the question-single view to this one, I got this message: `Your app has been updated to Meteor 1.0.3.1 from Meteor 1.0.3.2. Restart meteor to use the new release.` This has happened before and I'm wondering if we have checked in discrepant versions and this is what has caused some of the weird problems we've seen?

Aside from that weirdness, this looks good to merge! We might want to add a bit of whitespace between charts back in, but it doesn't seem like a big deal.

**Comment by macfarlandian** [comment]
@salspaugh that's possible i guess ... the version is stored in a tracked file in the `.meteor` directory so maybe if someone updates, pushes that file, and someone else checks it out, it forces a meteor update for that project. 

but if that were the case, the weirdness should be between branches, not within them.

**Comment by salspaugh** [comment]
Not sure I understand what you mean about between versus within -- it did happen switching between branches, but it was between two of your branches. It has also happened before when switching from one of Anna's branches back to mine. It looks like master was 1.0.3.1 and v2 is 1.0.3.2. Anyway it seems like all branches we care about are consistent now so no big deal.

**Comment by salspaugh** [comment]
Happened again when I went from v2 to your delete-dataset branch! So weird.

**Pull request merged**
