### PR TITLE
Question single view

### LINKED ISSUE #42: adapt old code to new QuestionSingle view

### PR DESCRIPTION
**Pull request by macfarlandian**
- click variables in sidebar to add/remove
- sidebar variables show active state
- dataset name removed from sidebar because we’re going to put it
somewhere else
- closes #42

@annaswigart @salspaugh this is working, as far as I can tell, but has a few issues. the primary one that might prevent us from merging is that the entire chart view redraws whenever you add/remove something. it’s more of an annoyance than a true bug IMO, but you may feel differently.

### CODE REVIEW

**Comment by macfarlandian** [comment]
also fun: i COMPLETELY FORGOT about the "discard/keep" part, so, nevermind

**Comment by macfarlandian** [comment]
ok, NOW it works

**Comment by salspaugh** [comment]
Looks good to me! :+1:

**Comment by annaswigart** [comment]
Looks good! My only comment is we may want to make the decision buttons bigger (very small right now).

**Pull request merged**
