### PR TITLE
Question modal and chart styles

### PR DESCRIPTION
**Pull request by annaswigart**
@salspaugh, @macfarlandian,

I've implemented a question modal with content filled in, but am still having trouble with connecting the right variable id to the modal. Any ideas on this??  I'm also hoping to make the question sections collapsable (with Reject collapsed by default, so it is out of the way).

Other changes include icons on the charts page and changing the nulls message/placement. Now includes percent of rows that are null. If there are no null values, I leave off the disclaimer. 

Also, note that I haven't rebased with the new v2 changes yet.

### CODE REVIEW

**Comment by salspaugh** [comment]
I think this is looking pretty cool! A couple of comments (aside from the things you already mentioned aren't working):

* The "Add" button to add a question on the modal is confusing because I wanted to hit it to add the variable to the question. Having "Save Changes" be the button you hit to (presumably) save the addition of the variable to the question isn't exactly right either. We should fiddle with how adding a question versus adding a variable looks in terms of what the buttons say and where they are located.
* I think at this point all our button, icon, tag, and font stylings may be all out of sync with one another, so at the end once the basic functionality is done, we should make one clean sweep to give everything a consistent look and feel.

But IMO once you get the save variable working: :+1: merge it.

**Comment by annaswigart** [comment]
ok, @salspaugh, @macfarlandian , I think we now have a functional tool!

Modal is implemented and still pretty ugly, but I wanted you guys to have this altogether. I've added a few style changes throughout, mostly on the charts page. Removed variable-specific notes for now (since we agreed they were not necessary). So now we have no notes fields anywhere, but maybe that's ok. See what you think.

The only major issue I'm having is that something (possibly having to do with the modal code?) is causing a LOT of console errors on the chart page (right when you load charts). This doesn't seem to have any noticeable effect on the experience, but I would still like to get it figured out. Haven't found a solution to this yet. The error is:
> Unrecognized logical operator: $$hashKey

**Comment by macfarlandian** [comment]
works great!

style note: the "number of nulls" message is a bit hard to associate with the correct variable now since it's kind of floating in the in-between space under the chart (or above the headline, it's hard to tell). it also is throwing off row alignment in some places and creating gaps in the columns: 

screen shot 2015-03-19 at 10 22 03 am

but I think as sara suggested we should do a high-level pass on visual consistency and aesthetics to catch and deal with issues like this.

**Comment by salspaugh** [comment]
Re: the `$$hashkey` error, I found this GitHub issue that seems potentially related -- https://github.com/lvbreda/Meteor_angularjs/issues/27. This isn't the same problem and that particular problem was probably resolved already (the issue is from two years ago) but I'm guessing it's a similar deal where meteor isn't handling this property well. Will poke around a bit more, though if it's not causing any functional problems I guess it doesn't matter that much.

**Comment by macfarlandian** [comment]
i've been trying to figure this out also ... i'm getting a lot of Mongo-related errors in general on the charts page now, and I think it has something to do with the initial rendering of the modal template (which I think is happening even though it's not visible) – it's expecting some variables to be on the $scope that aren't there yet.

**Comment by salspaugh** [comment]
After further inspection I think the `$$hashKey` problem is that meteor is confusing this `$$hashKey`, which is probably added by angular, for a logical operator like [these](http://docs.mongodb.org/manual/reference/operator/update/). However, I tried a few ways of removing this field and adding it back after the call to `findOne`, which is where the error is arising, and neither worked:

1. I tried fetching the whole collection and iterating over it to rename the property (and name it back later) but only an empty array is returned by fetch.
2. I tried updating the Question with the given `q_id` using `$rename` but I'm getting a `Not permitted. Untrusted code may only update documents by ID. [403]`. I think I could use `find` to get the document but I bet it would throw the same `$$hashKey` error, so that's kind of circular.

**Comment by salspaugh** [comment]
@macfarlandian Does this blog post seem relevant to the problem you describe? https://dweldon.silvrback.com/guards

**Comment by macfarlandian** [comment]
it might ... what I don't understand is how `$$hashKey` is even getting into the DB query in the first place

**Comment by salspaugh** [comment]
Re: the `$$hashKey` -- according to The Internet, angular adds it to objects you use `ng-repeat` with.

I think the "TypeError: Cannot read property` X `of undefined` errors all originate from uses of `find` or `findOne` that don't wait on the data to be available from meteor before executing. So we need to change that code pattern to eliminate those errors.

**Comment by salspaugh** [comment]
Just to reiterate there are two types of errors that I see:

1. Can't read property of undefined -- this is because the asynchronous nature of meteor means you can't operate immediately on what is returned from a meteor query, you have to wait for it to be ready.
2. The `$$hashKey` error -- this is because angular adds this property to objects and meteor doesn't like it.

**Comment by macfarlandian** [comment]
after agonizing over these for a while we figured them out – so we should be good to merge @salspaugh ?

**Comment by salspaugh** [comment]
Yes! Great job both of you and thanks!!!

**Pull request merged**
