### PR TITLE
Fix question page reload

### LINKED ISSUE #62: Stop page from reloading when a question is added.
Happens on the questions page.

### PR DESCRIPTION
**Pull request by macfarlandian**
@salspaugh closes #62

### CODE REVIEW

**Comment by salspaugh** [comment]
It still refreshes for me when I add a question. What should I do to debug this?

**Comment by salspaugh** [comment]
Also I should add that the question modal also has this same reloading behavior when you add a question.

**Comment by macfarlandian** [comment]
ugh. what browser are you using? i'm now seeing this work in firefox but not in chrome.

**Comment by salspaugh** [comment]
I'm using Chrome.

**Comment by macfarlandian** [comment]
@salspaugh i think this is fixed now, even though the solution is a stupid hack that makes me sad. tested in both firefox and chrome this time. let me know if it's still a problem.

**Comment by salspaugh** [comment]
Works! I don't understand what you did but :+1: good to merge.

**Comment by macfarlandian** [comment]
awesome ... i'll let you handle the merge since you've been doing all the
other stuff on that branch

**Comment by salspaugh** [comment]
Ok, will do.

**Pull request merged**
