### PR TITLE
rearrange some page titles and ui elements for more consistency

### LINKED ISSUE #61: Put name of page on all pages in consistent location and with consistent naming pattern.
Currently, the datasets page says **Your Datasets**, the questions page says **My Questions**, and the charts page says nothing. 

Proposed solution:
* **Datasets**
* **Charts**
* **Questions**

### LINKED ISSUE #69: Put name of current dataset on all views in consistent location.

### PR DESCRIPTION
**Pull request by macfarlandian**
@salspaugh @annaswigart this has some fairly significant UI changes, so see what you think … it also addresses a number of nagging UI inconsistencies (some of which didn’t have issues associated with them but were discussed in our last meeting)

- all views have a title in the upper right (fixes #61)
- dataset name is in navbar when active (fixes #69)
- navbar buttons are smaller, indicate active state
- sidebar now appears on the right, when present (allows for consistent
location of page title)

### CODE REVIEW

**Comment by salspaugh** [comment]
Hm. Well, we need to get clear on what our font scheme is. The text is now bolded all over the place, but it's being overused, which makes the interface look kind of cartoonish. Some suggestions (much on this theme):

* The buttons are still too small on the question detail page (re: @annaswigart last comment).
* The page title fonts don't need to be so huge and bold. This strongly draws the eye, but that information is not that detailed or important -- it's just a quick guide that people will quickly learn and want to glide over, but it's hard to do that with the aggressive size and bolding. We should experiment with other schemes and possibly consider other styles, for example like at the top of this GitHub PR page (a little icon and the user name in blue). It's clearly visible, but doesn't have the unnecessary magnetism of the large labels. 
* The current data set name is too large and bold -- it's larger and bolder than the other items on the navbar, but this makes no sense. Since it's only informational, it should actually be a much smaller font and not bold, like the size of the login text. Perhaps italicized, or not. I'd also make the navigation button text larger again -- it seems to have gotten shrunk. Lastly it'd be nice to see what the login username button looks like back next to the DataFramer logo, with the dataset name to the right side of that.
* Having the question detail page title be the actual question with the same styling as the other pages feels inconsistent -- in the other cases, the title corresponded to a place you could navigate to in the navbar, but this title is different. Perhaps the title should instead correspond to what type of page it is. The question text doesn't look good bold, because questions will tend to have at least five and usually more words, and it's hard to read a long sentence in that font weight. The letters are too large, bold, and spread out. A font weight similar to what GitHub uses for PRs and Issues would be a bit better though I'd even suggest tighter and smaller font.
* It doesn't make sense to have the dataset name at the top and in the side bar on the charts page.
* The page is uncomfortably wide to view, on all pages.
* The bolding of the row and column information is also weird.
* We still need some way to emphasize the Question button in the navbar that leads to the question page, since that is the point of the tool. Right now it's far too de-emphasized, especially relative to the plethora of other bolded labels. We could change it back to being a red button, or as an alternative example, look at how Facebook uses a bold white font for the home and user pages and more subtle greyed icons for the other pages. We could try other schemes instead too. But let's not toss out that idea of getting people to focus on asking questions as the key task of the tool. When people don't succeed at that, they quickly get frustrated with the tool, because they get into a situation where they want to be able to do more analysis, but they can't. We've seen this several times in our usability studies.
* The question notes still have a weird thing where the cursor jumps to before "Notes" but when you type, it starts after "Notes".

I actually like the variable list on the right hand side better.

**Comment by macfarlandian** [comment]
all good points ... will try to do a second iteration later today.

**Comment by macfarlandian** [comment]
@salspaugh here is a new version that addresses most of your notes and I think is generally just less of a mess, visually.

**Comment by salspaugh** [comment]
Thanks! Comments:

* I like the look of the "Charts" and "Questions" navbar buttons, but their location feels wrong. Suggest the order: DataFramer, login buttons, current dataset, Charts, Questions.
* The color of Questions is nice because it helps Questions stand out, but unfortunately it almost matches the blue color of the string columns. It would be nice if the (1) loading bar, (2) the "Add" buttons for questions and datasets, and (3) the Question button in the navbar were a consistent color that was distinguishable from the string datatype color. One option is to make the string color be the purple shades seen here: https://github.com/mbostock/d3/wiki/Ordinal-Scales#category20c, then we can make the other things a nice popping blue. Also the "Add to question" button that we are going to add should match the "Question" color on the navbar.
* In the side bar of the Charts page, a very light horizontal line that doesn't go all the way across but goes as far across as the search box and sits underneath the number of rows and columns line would help separate visually the different types of information present there.
* "Current Dataset" in the navbar is title cased, while all of the other informational messages are sentence-cased. Suggest changing to "Current dataset" for consistency and better readability.

**Comment by salspaugh** [comment]
Oh also I only just now noticed you removed the page titles entirely. Actually I like that better -- the titles were redundant with the active button, took up space, and made the weight of the page feel unevenly distributed.

**Comment by annaswigart** [comment]
Great progress, @macfarlandian! I especially like the right side nav and nav bar updates (though agree with reordering that @salspaugh suggests). 

Wanted to mention that I have some style changes (that should be compatible) in my branch add-q-to-modal, mostly for chart icons, positioning, and font weight. Working on getting the modal itself working now-- will set up a separate pull request by later tonight.

**Comment by macfarlandian** [comment]
i think the login menu ought to stay where it is, for IA reasons - it's the only item in the menu bar that isn't navigational, so I don't really want to mix it up in the middle of a bunch of nav links. but that's a relatively minor thing. i'll try to push another iteration before my class at 2 today.

**Comment by macfarlandian** [comment]
ok - a bunch of mostly cosmetic changes are active now, and I rebased on v2 to bring in the latest updates from other PRs.

Changing strings to purple was a good call, since bootstrap's primary accent color is blue. helps make the color usage a lot more consistent across the board.

**Comment by salspaugh** [comment]
Just noticed a bizarro bug. When you scroll down on the charts page, then click on "Questions", it loads the Questions page as far scrolled down as you were in the Charts page, so if you didn't realize this it looks like nothing loaded.

I think it's fine to merge this now and we can fix that later though.

**Comment by macfarlandian** [comment]
yeah i already filed an issue about it ... i know what the problem is, i
just haven't looked into how to fix it yet

https://github.com/macfarlandian/DataFramer/issues/81

**Comment by salspaugh** [comment]
Isn't it a separate problem though? Regardless of page lengths, we want the page to jump back up to the top when you switch from Charts to Questions and vice versa.

**Comment by macfarlandian** [comment]
well it'll do that automatically if there isn't weird invisible junk hiding
three screens deep in the DOM. two birds, one stone, and all that

**Comment by salspaugh** [comment]
Well what if there are really long lists of questions? Will it still jump back to the top?

**Comment by salspaugh** [comment]
It's also not weird invisible junk, they are the divs for the tooltips. Pretty straightforward.

**Comment by macfarlandian** [comment]
It should, because everything else in the view gets removed from the DOM
before the next view loads. I had to do the same thing with tooltips in V1
but rickshaw.js did its own garbage collection.

Two solutions I guess - either destroy tooltip instead of hiding, or keep
reusing the same element for all tooltips and on hiding put it someplace
where it won't cause trouble. Not sure which would be easier.

**Comment by salspaugh** [comment]
I think I tried reusing the same element and couldn't get it to work, though I could have been doing something else wrong. Whatever works is fine with me.

**Comment by salspaugh** [comment]
If it works, perhaps the easiest solution would be to create and destroy the tooltip on mouseover and mouseout, respectively.

**Pull request merged**
