### PR TITLE
Implement charts view.

### LINKED ISSUE #41: adapt old code to new Distributions view

### PR DESCRIPTION
**Pull request by salspaugh**
I updated the charts view. I addressed all the usability test feedback that we got except the fisheye issues and the ordering of charts versus ordering of columns list. Any thoughts on how to handle these are most welcome.

I also haven't implemented the body of the add-to-question modal, for two reasons:
1. I was thinking we might want to use some of @annaswigart's question index layout for that (so that they look similar). I don't have a really clear idea of what the modal content should look like, so let me know what you think.
2. I thought it might be helpful to everyone else to have the charts view sooner rather than later. We can work on the add-to-question modal after this is merged.

I just realized I forgot to add tooltips to the date charts, and the columns that were buggy before are still buggy now. I'll work on those. 

In the meantime, @annaswigart, @macfarlandian, let me know if this looks ok to merge!

Closes #41

### CODE REVIEW

**Comment by salspaugh** [comment]
Addendum: I think I'm rebased on the last version of v2 but not positive so until I do that you might want to wait on hitting "merge".

**Comment by annaswigart** [comment]
Nice work! Yes, definitely helpful to have this view to work with.

For the variables order, I think the most important thing we learned is that the sidebar and charts should be consistent. I would suggest having the default be alphabetical by type (like the sidebar is now), with an option to toggle to spreadsheet order for both the sidebar and the charts. The toggle is probably lower priority.

A few other things I notice:
- The sidebar does not stick to the top of the screen when you scroll the page (it disappears)
- The red and green colors look dull to me. Maybe we can use a color swatch website/app to choose colors? 
- Might consider removing the dark outline styling for bars on hover (I think the color change is enough)
- The questions nav title is still highlighted in charts view

**Comment by salspaugh** [comment]
> For the variables order, I think the most important thing we learned is that the sidebar and charts should be consistent

Yes, I know. That's not what I meant. I meant I can't figure out how to make AngularJS do this. :disappointed: If it used a stable sort, then `orderBy:name | orderBy:datatype` should work, but that's what I have now and it's not working. So I specifically meant what is the right syntax (or alternative approach (e.g., sorting in JS and adding a sort key).

> The red and green colors look dull to me. Maybe we can use a color swatch website/app to choose colors?

Yea, I spent a while messing with this ... I tried a few color selector websites, but ultimately went with the widely lauded ColorBrewer scales that come bundled with d3: https://github.com/mbostock/d3/wiki/Ordinal-Scales, specifically `d3.scale.category20b()`. The `d3.scale.category20c()` is brighter but has oranges instead of reds, so I went with the other one just to avoid changing too many of the original choices. The main challenge was finding four shades of the same color for the integer/float and date/time types because it was suggested in the usability feedback that they each be two different shades of the same color, but you also need lighter shades of each, for the highlighting. This made using ColorBrewer the easiest choice.

Shall I try to switch to `d3.scale.category20c()`?

> Might consider removing the dark outline styling for bars on hover

I did this because the color of the float on hover it made the bar a bit hard to see. Perhaps a subtly darker outline would help (e.g., not highlight the outline)?

> The questions nav title is still highlighted in charts view

Sorry, doesn't parse. What do you mean?

> The sidebar does not stick to the top of the screen when you scroll the page (it disappears)

True. I'll see if I can figure out how to fix this by looking at the old code (or if you know how to fix it let me know!).

**Comment by macfarlandian** [comment]
this looks super awesome

i second most of anna's points, though I don't mind the dark outlines (i
kind of like them aesthetically actually). i don't particularly mind the
colors either, but this a pretty minor thing to change either way.

for sorting, have you tried sorting in the database query rather than in
angular? might be easier, I think Mongo sorting is supposed to be stable.

for the sticky sidebar, i just used a css "position:fixed" solution because
the built in bootstrap "affix" plugin wasn't really working for some
reason. i made the height 100% and the width whatever the equivalent in
columns was (had to do it manually because fixing the position pulls it out
of the parent context). then I just offset the main column so they wouldn't
overlap.

**Comment by annaswigart** [comment]
> For the variables order, I think the most important thing we learned is that the sidebar and charts should be consistent
> Yes, I know. That's not what I meant. I meant I can't figure out how to make AngularJS do this.  If it used a stable sort, then orderBy:name | orderBy:datatype should work, but that's what I have now and it's not working. So I specifically meant what is the right syntax or alternative approach (e.g., sorting in JS and adding a sort key).

Gotcha. I'm not sure either-- I'll look into this.


> Shall I try to switch to d3.scale.category20c()?

I like this idea!


> I did this because the color of the float on hover it made the bar a bit hard to see. Perhaps a subtly darker outline would help (e.g., not highlight the outline)?

Sure, we could try that. 


> The questions nav title is still highlighted in charts view
> Sorry, doesn't parse. What do you mean?

Sorry, I mean the text in the nav bar that says "Questions" is still highlighted in red (as if it is indicating that I am on that page) in the charts view, when the "Charts" nav section should be highlighted instead.

**Comment by macfarlandian** [comment]
also forgot to mention: the "switch datatype" menu is not working for me.
it's just throwing errors.

**Comment by salspaugh** [comment]
> Sorry, I mean the text in the nav bar that says "Questions" is still highlighted in red

Aaah, I see. Actually it's just a red button. I guess it's confusing though. I was riffing off of: http://www.westelm.com/ like Marti suggested and trying to draw attention to that part of the tool. Guess it's not really working that way. Do you have any ideas for how to make it eye-catching but not confusing?

**Comment by salspaugh** [comment]
@macfarlandian Thanks for the impl tips and for noticing the error!

I'll let you guys know when I've made those changes -- probably tomorrow morning rather than tonight as I have to help @annaswigart with the question analysis thing from the Phase 1 in-lab evaluation.

**Comment by salspaugh** [comment]
So, regarding the sort, one issue is that the order you've put the variables in in the columns (which seems nice) is not alphabetical order. So I guess we have to add a separate "datatype sort index" field to make sure they stay in that order.

**Comment by salspaugh** [comment]
@macfarlandian Can you point me to the code or CSS that offsets the chart area (main column) to the right so that it doesn't overlap? Having trouble finding it.

**Comment by salspaugh** [comment]
Nevermind, I think I got it. Now I need to figure out how to make the navbar stay frozen, right?

**Comment by macfarlandian** [comment]
yeah.... i recommend just "position: fixed; height: 100%;" instead of
dicking around with bootstrap

**Comment by salspaugh** [comment]
Ok, I think this might be about ready to merge too.

Changes made:
* Column and chart sort order match.
* Side bar with column list stays on page with scroll.
* Date charts have a tooltip.
* Colors are updated to be brighter.
* Fixed the change datatype error.

Not fixed: 
* Some columns still fail to display properly.
* The old version had some code to wait for things to be ready before attempting to display that might make things look better when loading. I took it out just because I was trying to limit the complexity of the code I was working with at the time since I didn’t really get it all. I think I get that stuff now and can add it back in at some point, but it’d probably be nice to get these changes into v2 first.

Let me know if it's good to go.

**Comment by salspaugh** [comment]
Forgot to mention that for the chart sort to work properly you'll have to delete and re-upload the datasets, because I had to add a special dataset index variable to each column on load so that we could sort by the non-alphabetical order of `["string", "integer", "float", "date", "time"]`.

**Comment by annaswigart** [comment]
LGTM! I think it can be merged.

**Comment by macfarlandian** [comment]
looks great.

**Pull request merged**
